### PR TITLE
Adjust response codes

### LINKED ISSUE #53: HTTP Specification is not respected in regard to return codes
The HTTP specification is very clear in regard to the return codes which are expected to be returned by the server in the case of absent/invalid/outdated credentials.

Current version of the library does not respect the RFC in at least in two cases:

1. `DenyAllRule` always returns 403 Forbidden error code, even in the case there were no credentials provided. As per specification (https://tools.ietf.org/html/rfc7235#section-3.1), an error code 401 Unauthorised and a challenge header should be returned in this case.
2. Another case is `IAMClient` which returns 403 Forbidden error code in any case if a token string can't be validated by the remote endpoint. There are multiple reasons why validation can fail including, but not limited to the remote endpoint availability, malformed token and expired token. It is arguable that in these cases the response codes should be 500, 401 and 401 respectively to comply with the RFC.

Our API uses play-zhewbacca as a security filter and described behaviour breaks expectations of the client-side software. For instance, android devices do not refresh expired tokens because 403 error code returned by the server implies that the token is not expired yet.

I'd suggest to introduce one more `AuthResult` value, for example `AuthTokenInsufficient` or something which would encode the case of a valid token but insufficient rights/scopes. This type would be converted to the appropriate 403 Forbidden error code as per https://tools.ietf.org/html/rfc7231#section-6.5.3.

In any other case an error code 401 Unauthorised should be returned.

### PR DESCRIPTION
**Pull request by MikhailCodeRider**
Resolves #53 

introduce new auth result: AuthTokenInsufficient
changed response codes for cases:
1) in case auth failure return 401 instead of 403
2) in case empty token or invalid token return 401 instead of 403
3) return 403 only in case there is token but without proper scopes

fix deny and denyAll rules:
1) return 401 for deny rule in case empty token | invalid token
2) return 403 in case token is validated

### CODE REVIEW

File: src/main/scala/org/zalando/zhewbacca/RequestValidator.scala [hunk 1]
```diff
@@ -13,13 +13,14 @@ private[zhewbacca] object RequestValidator {
...
+      case AuthTokenInvalid => Left(Results.Unauthorized)
       case AuthTokenEmpty => Left(Results.Unauthorized)
+      case AuthTokenInsufficient => Left(Results.Forbidden)
     } recover {
       case NonFatal(e) =>
         logger.error(e.getMessage, e)
-        logger.debug("Request forbidden because of failure in Authentication Provider")
-        Left(Results.Forbidden)
+        logger.debug("Request unauthorized because of failure in Authentication Provider")
+        Left(Results.Unauthorized)
```
Comment (slavaschmidt) [inline src/main/scala/org/zalando/zhewbacca/RequestValidator.scala:23]: I'm wondering if this should be represented as 502 or 503 as this is not a client's mistake but internal problem

**Review by slavaschmidt — APPROVED** [review]
Impressive

File: src/main/scala/org/zalando/zhewbacca/SecurityRule.scala [hunk 2]
```diff
@@ -46,27 +46,35 @@ abstract case class ValidateTokenRule(
...
+}
+
+trait DenySecurityRule extends SecurityRule {
+  def authProvider: AuthProvider
+
+  private[this] val log = Logger(this.getClass)
 
   override def execute(nextFilter: (RequestHeader) => Future[Result], requestHeader: RequestHeader)(implicit ec: ExecutionContext): Future[Result] =
-    Future.successful(Results.Forbidden)
+    RequestValidator.validate(Scope.Empty, requestHeader, authProvider).flatMap[Result] {
```
Comment (dmitrykrivaltsevich) [inline src/main/scala/org/zalando/zhewbacca/SecurityRule.scala]: I'd suggest to always return 403 in case of 'deny all' because the server won't authorize the client with any amount of subsequent attempts.
```
Error 403: "The server understood the request, but is refusing to fulfill it. Authorization will not help and the request SHOULD NOT be repeated."
```

File: src/main/scala/org/zalando/zhewbacca/RequestValidator.scala (hunk 1 above)
Comment (MikhailCodeRider) [reply src/main/scala/org/zalando/zhewbacca/RequestValidator.scala:23]: The access token provided is expired, revoked, malformed, or
         invalid for other reasons.  The resource SHOULD respond with
         the HTTP 401 (Unauthorized) status code.  The client MAY
         request a new access token and retry the protected resource
         request.


-->  invalid for other reasons. 

i would go for 401

Comment (slavaschmidt) [reply src/main/scala/org/zalando/zhewbacca/RequestValidator.scala:23]: well, in general 4xx is a client problem which means client is doing something wrong and should change the data before retrying 
in this case it is definitely a server problem, right? So this _should_ be something 5xx
In the passage you're referring to "invalid for other reasons" applies to the token, not in general and in the situation at hand we just can't tell if it is valid or not. And this is server's fault.

File: src/main/scala/org/zalando/zhewbacca/SecurityRule.scala (hunk 2 above)
Comment (slavaschmidt) [reply src/main/scala/org/zalando/zhewbacca/SecurityRule.scala]: This is not of a huge importance, but the "spirit" of these error codes is like following:
401 - Hey, your credentials are invalid for some reason, get valid one and come back
403 - Hey, your valid credentials are not allowing you to access this, only come back after becoming more powerful

But in both cases the client is doing something wrong and might fix the situation in one way or another. In this specific case the client can to nothing about this which suggests the server should say something about the _resource_, not about the request

**Comment by dmitrykrivaltsevich** [comment]
👍

**Review by dmitrykrivaltsevich — APPROVED** [review]

**Comment by dmitrykrivaltsevich** [comment]
@MikhailLitvin and @slavaschmidt , thank you for the contribution!
